# Generated by Django 5.1.2 on 2024-11-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transcript_file', models.FileField(upload_to='transcripts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
