# Generated by Django 5.1.2 on 2024-12-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_delete_audiofile_transcript_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='transcript_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/transcripts/'),
        ),
    ]
