# Generated by Django 5.1.2 on 2024-12-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0004_alter_transcript_transcript_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='transcript_file',
        ),
        migrations.AddField(
            model_name='transcript',
            name='transcript_text',
            field=models.TextField(default=''),
        ),
    ]
