# Generated by Django 5.2.6 on 2025-11-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0006_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(default='', max_length=255, blank=True),
        ),
    ]
