# Generated by Django 5.2.6 on 2025-11-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0009_alter_topic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField(default='')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcription.transcript')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_present', models.BooleanField(default=False)),
                ('relevant_section', models.TextField(default='')),
                ('user_validation', models.BooleanField(default=False)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='transcription.chunk')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='transcription.topic')),
            ],
        ),
        migrations.AddField(
            model_name='chunk',
            name='topics',
            field=models.ManyToManyField(related_name='chunks', through='transcription.Tag', to='transcription.topic'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('chunk', 'topic'), name='uniq_chunk_topic'),
        ),
    ]
