# Generated by Django 5.2.6 on 2026-01-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0010_chunk_tag_chunk_topics_tag_uniq_chunk_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('general', 'General'), ('topic', 'Topic')], default='general', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='transcription.topic')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='transcription.transcript')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('summary_type', 'general'), ('topic__isnull', True)), models.Q(('summary_type', 'topic'), ('topic__isnull', False)), _connector='OR'), name='summary_topic_required_for_topic_type')],
            },
        ),
    ]
