# Generated by Django 5.2.6 on 2026-06-20 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0013_topic_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('add_demo', 'Add demo'), ('transcription', 'Transcription'), ('tagging', 'Tagging'), ('summary', 'Summary')], max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('related_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
