# Generated by Django 5.2.6 on 2026-07-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0014_backgroundjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundjob',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
