# Generated by Django 5.2.6 on 2026-07-06 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0015_backgroundjob_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='kind',
            field=models.CharField(choices=[('transcription', 'Transcription'), ('tagging', 'Tagging'), ('summary', 'Summary')], max_length=50),
        ),
        migrations.CreateModel(
            name='TranscriptionJobMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('audio_duration_sec', models.FloatField(blank=True, null=True)),
                ('normalized_duration_sec', models.FloatField(blank=True, null=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('max_concurrent_chunks', models.PositiveIntegerField(default=1)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('worker_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration_sec', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_type', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('background_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_metric', to='transcription.backgroundjob')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_metrics', to='transcription.transcript')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionChunkMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('start_time_sec', models.FloatField()),
                ('duration_sec', models.FloatField()),
                ('split_depth', models.PositiveIntegerField(default=0)),
                ('chunk_file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ffmpeg_duration_sec', models.FloatField(blank=True, null=True)),
                ('openai_duration_sec', models.FloatField(blank=True, null=True)),
                ('total_duration_sec', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=20)),
                ('error_type', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('job_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_metrics', to='transcription.transcriptionjobmetric')),
            ],
            options={
                'indexes': [models.Index(fields=['job_metric', 'chunk_index'], name='transcripti_job_met_ee8547_idx'), models.Index(fields=['started_at', 'finished_at'], name='transcripti_started_5691ed_idx')],
            },
        ),
    ]
