# Generated by Django 5.2.6 on 2026-08-03 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0016_alter_backgroundjob_kind_transcriptionjobmetric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('billing_unit', models.CharField(choices=[('text_tokens', 'Text tokens'), ('audio_duration', 'Audio duration')], max_length=30)),
                ('input_rate_per_million', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('cached_input_rate_per_million', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('output_rate_per_million', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('rate_per_minute', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', 'provider', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='TaskPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('transcription', 'Transcription'), ('summary', 'Summary'), ('tagging', 'Tagging')], max_length=30)),
                ('multiplier', models.DecimalField(decimal_places=6, max_digits=12)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_pricings', to=settings.AUTH_USER_MODEL)),
                ('model_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_pricings', to='transcription.modelprice')),
            ],
            options={
                'ordering': ['-effective_from', 'task_type'],
            },
        ),
        migrations.AddIndex(
            model_name='modelprice',
            index=models.Index(fields=['provider', 'model_name', 'billing_unit', 'currency', 'effective_from'], name='transcripti_provide_9b58f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelprice',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='model_price_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='modelprice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('input_rate_per_million__isnull', True), ('input_rate_per_million__gte', 0), _connector='OR'), models.Q(('cached_input_rate_per_million__isnull', True), ('cached_input_rate_per_million__gte', 0), _connector='OR'), models.Q(('output_rate_per_million__isnull', True), ('output_rate_per_million__gte', 0), _connector='OR'), models.Q(('rate_per_minute__isnull', True), ('rate_per_minute__gte', 0), _connector='OR')), name='model_price_nonnegative_rates'),
        ),
        migrations.AddConstraint(
            model_name='modelprice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('billing_unit', 'text_tokens'), ('input_rate_per_million__isnull', False), ('output_rate_per_million__isnull', False), ('rate_per_minute__isnull', True)), models.Q(('billing_unit', 'audio_duration'), ('cached_input_rate_per_million__isnull', True), ('input_rate_per_million__isnull', True), ('output_rate_per_million__isnull', True), ('rate_per_minute__isnull', False)), _connector='OR'), name='model_price_rates_match_unit'),
        ),
        migrations.AddIndex(
            model_name='taskpricing',
            index=models.Index(fields=['task_type', 'model_price', 'effective_from'], name='transcripti_task_ty_3f5b2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskpricing',
            constraint=models.CheckConstraint(condition=models.Q(('multiplier__gt', 0)), name='task_pricing_positive_multiplier'),
        ),
        migrations.AddConstraint(
            model_name='taskpricing',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='task_pricing_end_after_start'),
        ),
    ]
