# Generated by Django 5.2.6 on 2026-08-03 10:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0017_modelprice_taskpricing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('transcription', 'Transcription'), ('summary', 'Summary'), ('tagging', 'Tagging')], max_length=30)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('reconciliation_required', 'Reconciliation required'), ('simulated', 'Simulated')], default='pending', max_length=30)),
                ('billing_unit', models.CharField(choices=[('text_tokens', 'Text tokens'), ('audio_duration', 'Audio duration')], max_length=30)),
                ('usage_source', models.CharField(choices=[('provider', 'Provider'), ('duration', 'Duration'), ('simulated', 'Simulated')], max_length=20)),
                ('input_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cached_input_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('audio_duration_seconds', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('base_cost', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('multiplier', models.DecimalField(decimal_places=6, max_digits=12)),
                ('billed_cost', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('calculation_details', models.JSONField(blank=True, default=dict)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='transcription.modelprice')),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='transcription.summary')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='transcription.tag')),
                ('task_pricing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='transcription.taskpricing')),
                ('transcript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='transcription.transcript')),
                ('transcription_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='transcription.transcriptionchunkmetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='transcripti_user_id_ef8bde_idx'), models.Index(fields=['task_type', 'occurred_at'], name='transcripti_task_ty_0f0c6c_idx'), models.Index(fields=['status', 'occurred_at'], name='transcripti_status_18652a_idx'), models.Index(fields=['transcript', 'occurred_at'], name='transcripti_transcr_fb8eb0_idx'), models.Index(fields=['summary', 'occurred_at'], name='transcripti_summary_1694e9_idx'), models.Index(fields=['tag', 'occurred_at'], name='transcripti_tag_id_9ea9ed_idx'), models.Index(fields=['transcription_chunk', 'occurred_at'], name='transcripti_transcr_ddbfd0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('audio_duration_seconds__isnull', True), ('audio_duration_seconds__gte', 0), _connector='OR'), models.Q(('base_cost__isnull', True), ('base_cost__gte', 0), _connector='OR'), models.Q(('billed_cost__isnull', True), ('billed_cost__gte', 0), _connector='OR'), ('multiplier__gt', 0)), name='usage_event_nonnegative_values'), models.CheckConstraint(condition=models.Q(models.Q(('audio_duration_seconds__isnull', True), ('billing_unit', 'text_tokens')), models.Q(('billing_unit', 'audio_duration'), ('cached_input_tokens__isnull', True), ('input_tokens__isnull', True), ('output_tokens__isnull', True)), _connector='OR'), name='usage_event_quantity_matches_unit'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'succeeded'), _negated=True), models.Q(('base_cost__isnull', False), ('billed_cost__isnull', False)), _connector='OR'), name='usage_event_succeeded_has_costs'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'simulated'), _negated=True), models.Q(('base_cost', 0), ('billed_cost', 0), ('usage_source', 'simulated')), _connector='OR'), name='usage_event_simulated_is_zero')],
            },
        ),
    ]
