# Generated by Django 5.2.6 on 2026-08-07 04:57

from django.db import migrations


PERMISSION_DEFINITIONS = (
    ("view_all_usage", "Can view usage for all users", "Usage Viewers"),
    (
        "manage_usage_pricing",
        "Can manage usage pricing",
        "Usage Pricing Managers",
    ),
)


def create_usage_permission_groups(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="transcription",
        model="usageevent",
    )
    for codename, name, group_name in PERMISSION_DEFINITIONS:
        permission, _ = Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        if permission.name != name:
            permission.name = name
            permission.save(update_fields=["name"])
        group, _ = Group.objects.get_or_create(name=group_name)
        group.permissions.add(permission)


def remove_usage_permissions_from_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    for codename, _name, group_name in PERMISSION_DEFINITIONS:
        group = Group.objects.filter(name=group_name).first()
        permission = Permission.objects.filter(
            content_type__app_label="transcription",
            content_type__model="usageevent",
            codename=codename,
        ).first()
        if group is not None and permission is not None:
            group.permissions.remove(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('transcription', '0018_usageevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usageevent',
            options={'ordering': ['-occurred_at', '-id'], 'permissions': [('view_all_usage', 'Can view usage for all users'), ('manage_usage_pricing', 'Can manage usage pricing')]},
        ),
        migrations.RunPython(
            create_usage_permission_groups,
            remove_usage_permissions_from_groups,
        ),
    ]
