# Generated by Django 5.2.6 on 2026-09-27 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0021_chunk_reconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='provider_outcome',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_delivery', 'Awaiting delivery'), ('not_billable', 'Not billable'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('reconciliation_required', 'Reconciliation required'), ('simulated', 'Simulated')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='TranscriptionBillingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_state', models.CharField(choices=[('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('billing_state', models.CharField(choices=[('pending', 'Pending'), ('finalized', 'Finalized'), ('not_billable', 'Not billable'), ('reconciliation_required', 'Reconciliation required')], default='pending', max_length=30)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background_job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_attempt', to='transcription.backgroundjob')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_attempts', to='transcription.transcript')),
            ],
        ),
        migrations.AddField(
            model_name='usageevent',
            name='transcription_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='transcription.transcriptionbillingattempt'),
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'awaiting_delivery'), _negated=True), models.Q(('billed_cost__isnull', True), ('transcription_attempt__isnull', False)), _connector='OR'), name='usage_event_deferred_charge'),
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'not_billable'), _negated=True), models.Q(('billed_cost', 0), ('billed_cost__isnull', False)), _connector='OR'), name='usage_event_nonbillable_zero'),
        ),
        migrations.AddConstraint(
            model_name='transcriptionbillingattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('billing_state', 'pending'), ('delivered_at__isnull', True), ('processing_state', 'processing')), models.Q(('billing_state', 'not_billable'), ('delivered_at__isnull', True), ('processing_state', 'failed')), models.Q(('billing_state__in', ['pending', 'finalized', 'reconciliation_required']), ('delivered_at__isnull', False), ('processing_state', 'delivered')), _connector='OR'), name='transcription_billing_state_matches_delivery'),
        ),
    ]
