# Generated by Django 5.2.6 on 2026-09-27 04:04

from django.db import migrations, models


def seed_lock(apps, schema_editor):
    apps.get_model('transcription', 'PricingWriteLock').objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0022_usageevent_provider_outcome_alter_usageevent_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingWriteLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RunPython(seed_lock, migrations.RunPython.noop),
    ]
